// Proving the ladder did not choose the world it dealt you.
//
// A recruit turned this project down partly on the grounds that
// pre-verifying seeds is bad for integrity, and the sharp half of that
// is correct. The pool is built in advance, which means the operator
// knows every world in it before any of them is dealt - and the
// operator plays on this ladder. Nothing in the draw stopped them
// dealing themselves a world they had already studied, and "we would
// not do that" is precisely the kind of assurance this project exists
// to stop asking players for.
//
// So the draw stops being a choice and becomes a calculation:
//
//   1. A season opens with a random secret S. SHA256(S) is committed to
//      git - published, timestamped, and impossible to revise later.
//   2. Every draw takes its randomness from HMAC(S, matchId). Given the
//      candidates and the matchId, the dealt seed is FIXED. The server
//      does not get an opinion.
//   3. Each match records a commitment to what was dealt, published the
//      moment the match exists, and openable once it has finished.
//   4. At season close S is published. Anyone can then replay every
//      draw of the season with scripts/verifyDraws.ts and check the
//      seed the server dealt is the seed the arithmetic demands.
//
// WHAT THIS DOES NOT PROVE, stated here because the alternative is
// letting the README imply otherwise:
//
//   - The CANDIDATE LIST is not proven honest. A malicious operator
//     could hide pool rows from the scan at draw time and the
//     arithmetic downstream of it would still check out. Closing that
//     needs the pool itself published, which burns the pool - the same
//     trade that keeps the pool secret in the first place.
//   - matchId is generated by the server immediately before the draw,
//     so an operator willing to re-roll it can shop for an outcome. It
//     costs them a discarded match id per attempt and leaves no trace.
//     The fix is a draw key that mixes in something the server has to
//     commit to first - a nonce from each client, recorded on the queue
//     row before pairing - and it needs a mod change, so it is logged
//     in TODO.md rather than half-built here.
//   - Nothing here touches memorisation. A player who recognises a
//     world at spawn is a pool-rotation problem, not a draw problem.
//
// Verification is retrospective by design. Until S is published nobody
// outside can check a single draw, which is exactly why the season
// boundary matters: it is the point at which the claim becomes falsifiable.
import { createHash, createHmac, randomBytes, randomInt } from 'node:crypto';

/** Bumped if the derivation or the commitment pre-image ever changes. */
export const DRAW_SCHEME = 'alt-draw-v1';

export interface SeasonConfig {
	seasonId: string;
	/** Hex. Null when no season is configured - see drawMode below. */
	secret: string | null;
}

/**
 * The season, from the environment.
 *
 * A MISSING SECRET DOES NOT FAIL A MATCH. The ladder has to keep
 * running on a deploy that has not been given a season file, the same
 * way absent split rules degrade to loose checking rather than refusing
 * honest runs.
 *
 * But it must not degrade SILENTLY, which is the difference between
 * this and a default. A draw made without a secret is stamped
 * 'unverifiable' on the match record and stays that way forever, so the
 * season audit reports it as unaudited rather than as passing. A check
 * that cannot see anything has to say so.
 */
export function seasonFromEnv(): SeasonConfig {
	const secret = process.env.SEASON_SECRET ?? '';
	return {
		seasonId: process.env.SEASON_ID ?? 'unset',
		secret: secret.length > 0 ? secret : null,
	};
}

export type DrawMode = 'derived' | 'unverifiable';

/**
 * Draws an integer in [0, n).
 *
 * Deterministic given (secret, matchId) - the same pair walks the same
 * sequence every time, which is what makes a draw reproducible by
 * somebody who was not there.
 */
export type Picker = (n: number) => number;

/**
 * The keystream a draw is made from.
 *
 * HMAC-SHA256 over a counter, consumed 32 bits at a time, with
 * rejection sampling to keep the distribution flat. Taking a modulus of
 * a raw 32-bit word would quietly bias the draw toward low indices, and
 * a biased draw over a pool where type depth already varies is a thumb
 * on the scale nobody would see.
 */
export function derivedPicker(secret: string, matchId: string): Picker {
	let counter = 0;
	let block = Buffer.alloc(0);
	let offset = 0;

	const next = (): number => {
		if (offset + 4 > block.length) {
			block = createHmac('sha256', Buffer.from(secret, 'hex'))
				.update(`${DRAW_SCHEME}:${matchId}:${counter++}`)
				.digest();
			offset = 0;
		}
		const value = block.readUInt32BE(offset);
		offset += 4;
		return value;
	};

	return (n: number): number => {
		if (n <= 1) return 0;
		// Largest multiple of n that fits in 32 bits; anything above it
		// would wrap unevenly, so it is thrown away and redrawn.
		const limit = Math.floor(0x1_0000_0000 / n) * n;
		let v = next();
		while (v >= limit) v = next();
		return v % n;
	};
}

/** The fallback when no season is configured. Not reproducible, and says so. */
export function randomPicker(): Picker {
	return (n: number) => (n <= 1 ? 0 : randomInt(n));
}

export function pickerFor(season: SeasonConfig, matchId: string): {
	pick: Picker;
	mode: DrawMode;
} {
	return season.secret
		? { pick: derivedPicker(season.secret, matchId), mode: 'derived' }
		: { pick: randomPicker(), mode: 'unverifiable' };
}

/**
 * One candidate, reduced to what the draw actually uses.
 *
 * Type and id only. The seeds themselves are deliberately absent: the
 * candidate list is recorded on the match row so the draw can be
 * replayed later, and a list of seeds on a match row is the pool
 * leaking out through the audit trail.
 */
export interface DrawCandidate {
	seedPairId: string;
	seedType: string;
}

/** `type:id`, which is the form the candidate list is recorded in. */
export function candidateKey(c: DrawCandidate): string {
	return `${c.seedType}:${c.seedPairId}`;
}

/**
 * The draw order, from a candidate list and a picker.
 *
 * SORTED FIRST, and that is not tidiness. Candidates arrive from a
 * DynamoDB Scan, whose order is arbitrary - stable for a given table
 * state, but not something a verifier can reconstruct. Deriving the
 * order from an unsorted list would make the draw depend on a fact
 * nobody can check, and the whole scheme would prove nothing.
 *
 * Type first, then seeds within it, mirroring the live draw: a type's
 * share of the draw must not be its share of the pool, or filling a
 * shortage in one type would quietly make it the common opening.
 *
 * The full order is returned rather than a single winner so the
 * fallback order is reproducible too - if the first candidate could not
 * be claimed, the audit can still say the second one was the right
 * second one.
 */
export function deriveDrawOrder(
	candidates: DrawCandidate[],
	pick: Picker,
): string[] {
	const byType = new Map<string, string[]>();
	for (const key of candidates.map(candidateKey).sort()) {
		const type = key.slice(0, key.indexOf(':'));
		const list = byType.get(type);
		if (list) list.push(key);
		else byType.set(type, [key]);
	}

	const types = Array.from(byType.keys()).sort();
	shuffle(types, pick);

	const ordered: string[] = [];
	for (const type of types) {
		const list = byType.get(type)!;
		shuffle(list, pick);
		ordered.push(...list);
	}
	return ordered;
}

/** Fisher-Yates, driven by the picker so it is reproducible. */
function shuffle<T>(items: T[], pick: Picker): void {
	for (let i = items.length - 1; i > 0; i--) {
		const j = pick(i + 1);
		[items[i], items[j]] = [items[j], items[i]];
	}
}

/**
 * What a match records about its own draw.
 *
 * `candidates` is the input the draw ran over, and without it the draw
 * cannot be replayed: it depends on both players' seen-seed history,
 * which has moved on by the time anyone audits. It is ids, never seeds,
 * and it is never served by the API - pool depth per type is exactly
 * the map of where the ladder is thin that CLAUDE.md keeps out of git.
 */
export interface DrawRecord {
	scheme: string;
	seasonId: string;
	mode: DrawMode;
	candidates: string[];
	/** Where the dealt seed sat in the derived order. 0 in the normal case. */
	index: number;
}

export interface SealedDraw {
	/** Published as soon as the match exists. */
	commitment: string;
	/** Withheld until the match is over, then published with it. */
	nonce: string;
}

/**
 * The commitment to what was dealt.
 *
 * The nonce is what makes it worth publishing during a live match. The
 * pool holds a few hundred rows, so a bare hash of a seed id is not
 * hidden at all - anyone with the pool could try every id and read the
 * commitment straight off. With a nonce it says nothing until the
 * nonce is released, and it still cannot be moved afterwards.
 */
export function commitDraw(
	seasonId: string,
	matchId: string,
	nonce: string,
	pair: { seedPairId: string; overworldSeed: number; netherSeed: number },
): string {
	return createHash('sha256').update([
		DRAW_SCHEME,
		seasonId,
		matchId,
		nonce,
		pair.seedPairId,
		String(pair.overworldSeed),
		String(pair.netherSeed),
	].join('|')).digest('hex');
}

export function sealDraw(
	seasonId: string,
	matchId: string,
	pair: { seedPairId: string; overworldSeed: number; netherSeed: number },
): SealedDraw {
	const nonce = randomBytes(16).toString('hex');
	return { nonce, commitment: commitDraw(seasonId, matchId, nonce, pair) };
}

/** SHA256 of the season secret - the value published at season open. */
export function seasonCommitment(secret: string): string {
	return createHash('sha256').update(Buffer.from(secret, 'hex')).digest('hex');
}
